import fs from 'node:fs';
import assert from 'node:assert/strict';

const ts=fs.readFileSync('web/src/match-pacing.ts','utf8');
const cpu=fs.readFileSync('web/src/cpu.ts','utf8');
const css=fs.readFileSync('web/match-pacing.css','utf8');
const mobileCss=fs.readFileSync('web/mobile-landscape-v6.css','utf8');
const html=fs.readFileSync('web/index.html','utf8');

assert.match(html,/match-pacing\.css/,'match animation CSS must be loaded');
assert.match(html,/dist\/match-pacing\.js/,'match animation script must be loaded');
assert.match(ts,/async function playVisibleActionSteps/,'action presentation must be an awaitable blocking sequence');
assert.match(cpu,/await playVisibleActionSteps\(event,nextState\)/,'engine event playback must wait for presentation before progressing');
assert.match(ts,/matchRecapBlocking=true/,'player input must be blocked while card motion is active');
assert.match(ts,/stopImmediatePropagation\(\)/,'presentation must prevent accidental actions');
assert.match(ts,/showCardToField/,'played cards must move onto the table rather than appear in a recap modal');
assert.match(ts,/showDeckReveal/,'the deck card must visibly reveal before play continues');
assert.match(ts,/showCaptureMove/,'captured cards must visibly move toward the capturing side');
assert.match(ts,/captureGroups/,'hand and deck captures must be separated by card month when possible');
assert.match(ts,/function hideCapturedFieldCards\(cards:number\[\]\)/,'capture motion must explicitly hide authoritative field-card sources before the copy moves');
assert.match(ts,/button\.classList\.add\("capture-source-hidden"\)/,'the actual field-card DOM must disappear at capture start');
assert.match(ts,/hideCapturedFieldCards\(cards\);[\s\S]*--capture-x/,'the field source must be hidden before capture-to-rail motion begins');
assert.match(ts,/if\(!completed\)restoreHiddenFieldCards\(\)/,'a failed animation must restore temporarily hidden field cards');
assert.match(css,/\.field-card-button\.capture-source-hidden\{visibility:hidden!important\}/,'captured card faces must disappear without collapsing their two-row field slots');
assert.match(ts,/function reflectCapturedRail\(event:ActionEvent,nextState:Snapshot\|null\)/,'capture completion must have an explicit immediate destination update');
assert.match(ts,/reflectCapturedRail\(event,nextState\);\s*layer\.remove\(\)/,'captured cards must appear in the capture rail at the instant capture motion finishes');
assert.match(ts,/function isTurnProgressEvent\(event:ActionEvent\)\{return event\.type==="play"\|\|event\.type==="cpu_step";\}/,'only real turn-progress events may drive hand/deck motion');
assert.match(ts,/function hasDeckReveal\(event:ActionEvent\)\{return isTurnProgressEvent\(event\)&&Number\.isInteger\(event\.drawnCard\);\}/,'stale drawnCard data on capture events must never create a phantom deck animation');
assert.match(ts,/if\(hasDeckReveal\(event\)\)\{/,'deck reveal must be gated by the validated deck-event predicate');
assert.match(ts,/if\(!hasHandPlay\(event\)&&!hasDeckReveal\(event\)&&event\.capturedCards\?\.length\)/,'capture-only events must render as capture-only without replaying hand/deck motion');
assert.doesNotMatch(ts,/match-action-recap|match-action-card/,'the old full-board recap card must be removed');
assert.match(ts,/board\.clientWidth/,'animation distances must be derived from the landscape board width');
assert.match(ts,/board\.clientHeight/,'hand extraction must be derived from the landscape board height');
assert.match(ts,/function visualBoardOffset\(horizontal:number,vertical:number\)/,'animation must convert visual landscape axes into local rotated-canvas axes');
assert.match(ts,/rotated\?\{x:vertical,y:-horizontal\}:\{x:horizontal,y:vertical\}/,'virtual landscape must swap X/Y so visible horizontal motion stays horizontal after the 90 degree canvas rotation');
assert.match(ts,/--deck-x/,'deck extraction must receive an explicit local X offset');
assert.match(ts,/--deck-y/,'deck extraction must receive an explicit local Y offset');
assert.match(ts,/--capture-x/,'capture motion must receive a board-relative X distance');
assert.match(ts,/--capture-y/,'capture motion must receive a board-relative Y distance');
assert.match(css,/\.table-action-layer\{position:absolute;inset:0/,'all action motion must be contained by the landscape board');
assert.match(css,/\.table-action-card/,'played-card motion must be rendered on the table');
assert.match(css,/\.table-draw-card/,'draw animation must include a visible card flip');
assert.match(css,/\.table-deck-source/,'deck draw must visibly originate from an on-table deck stack');
assert.match(css,/deck-pull-landscape/,'deck draw must use an explicit landscape path');
assert.match(css,/var\(--deck-x\)/,'deck path must support orientation-aware X');
assert.match(css,/var\(--deck-y\)/,'deck path must support orientation-aware Y');
assert.match(css,/\.table-capture-group/,'capture motion must be rendered toward a capture rail');
assert.doesNotMatch(css,/\d+vh|\d+vw/,'match pacing paths must never use portrait-browser viewport units');
assert.doesNotMatch(css,/\.match-action-recap|\.match-action-card/,'old modal-like recap presentation must not remain');
assert.match(css,/\.hand-card-button:disabled,\.field-card-button:disabled\{opacity:1\}/,'temporarily disabled cards must stay opaque');
assert.doesNotMatch(cpu,/if\(event\.capturedCards\?\.length\)toast\(/,'ordinary capture events must not create accumulating toast notifications');
assert.doesNotMatch(cpu,/if\(event\.newYakuMask\)toast\(/,'ordinary yaku events must not create accumulating toast notifications');
assert.match(cpu,/function matchEffectHost\(\)\{return document\.documentElement\.classList\.contains\("mobile-webapp"\)\?app:document\.body;\}/,'mobile match effects must be mounted inside the rotated landscape application');
assert.match(cpu,/matchEffectHost\(\)\.append\(layer\)/,'koi/agari/shuffle effects must use the landscape-aware effect host');
assert.match(mobileCss,/\.match-screen>\.modal-layer\{position:absolute;inset:0/,'koi/agari and other match modals must use the landscape screen as their coordinate system');
assert.match(mobileCss,/#app>\.fx-layer\{position:absolute/,'dynamic koi/agari effects must be anchored inside the virtual landscape app');
assert.match(mobileCss,/html\.mobile-webapp\.phone-landscape \.agari-yaku-card/,'agari yaku presentation must have phone landscape sizing');
assert.match(mobileCss,/\.callout \.particle\{display:none!important\}/,'phone koi/agari callouts must avoid particle-heavy rendering');
assert.match(mobileCss,/chrome-mobile \.card[^\n]*filter:none!important/,'Chrome mobile must not run expensive card filters during match animation');
assert.match(css,/phone-landscape \.table-action-card[\s\S]*filter:none!important/,'phone action animations must remove expensive drop-shadow filters');
assert.match(ts,/async function showReadyGate\(\)/,'CPU start must expose a visible ready gate after dealing');
assert.match(cpu,/await animateNewRoundIfNeeded\(true\);\s*await showReadyGate\(\);\s*await releaseCpuAfterReady\(\);/,'initial CPU release must occur only after shuffle, deal and ready presentation');

const acceptStart=cpu.indexOf('async function acceptSnapshot');
const acceptEnd=cpu.indexOf('function recordHistory',acceptStart);
assert.ok(acceptStart>=0&&acceptEnd>acceptStart,'acceptSnapshot must exist');
const acceptBlock=cpu.slice(acceptStart,acceptEnd);
const animateIndex=acceptBlock.indexOf('await animateEvent(visibleEvent,next)');
const commitIndex=acceptBlock.indexOf('snapshot=next');
const renderIndex=acceptBlock.lastIndexOf('renderMatch()');
assert.ok(animateIndex>=0&&commitIndex>animateIndex,'the visible action must finish before the authoritative next snapshot is committed to the board');
assert.ok(renderIndex>commitIndex,'the post-action board and settlement UI must render only after animation completion');
assert.doesNotMatch(cpu,/event\.capturedCards\?\.length\)await showCaptureTrail/,'legacy capture trail must not add a second delayed capture after the board-first capture motion');
assert.match(cpu,/async function animateEvent\(event:ActionEvent,nextState:Snapshot\|null=snapshot\)/,'event animation must receive the upcoming authoritative state without displaying it early');
assert.match(cpu,/await showCallout\("effect\.agari\.text"\);[\s\S]*confirmedSettlementYaku\(event,nextState\)/,'agari and confirmed yaku must be presented from the upcoming settlement state before settlement UI is committed');

console.log('board-first DS-style match animation contract: PASS');
