#include <png.h>
#include <nlohmann/json.hpp>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <set>
#include <stdexcept>
#include <string>
#include <vector>
using json=nlohmann::json; namespace fs=std::filesystem;
struct Rect{int x,y,w,h;};
static bool overlaps(const Rect&a,const Rect&b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
static std::vector<std::uint8_t> read_png(const fs::path&p,int&w,int&h){png_image im{};im.version=PNG_IMAGE_VERSION;if(!png_image_begin_read_from_file(&im,p.string().c_str()))throw std::runtime_error("PNG_READ_BEGIN_FAILED");im.format=PNG_FORMAT_RGBA;w=(int)im.width;h=(int)im.height;std::vector<std::uint8_t> px(PNG_IMAGE_SIZE(im));if(!png_image_finish_read(&im,nullptr,px.data(),0,nullptr)){png_image_free(&im);throw std::runtime_error("PNG_READ_FAILED");}png_image_free(&im);return px;}
static void write_png(const fs::path&p,int w,int h,const std::vector<std::uint8_t>&px){png_image im{};im.version=PNG_IMAGE_VERSION;im.width=w;im.height=h;im.format=PNG_FORMAT_RGBA;fs::create_directories(p.parent_path());if(!png_image_write_to_file(&im,p.string().c_str(),0,px.data(),0,nullptr))throw std::runtime_error("PNG_WRITE_FAILED");}
static std::vector<std::uint8_t> contain(const std::vector<std::uint8_t>&src,int sw,const Rect&r,int ow,int oh){std::vector<std::uint8_t>out((size_t)ow*oh*4,0);double scale=std::min((double)ow/r.w,(double)oh/r.h);int fw=std::max(1,(int)std::lround(r.w*scale)),fh=std::max(1,(int)std::lround(r.h*scale));int ox0=(ow-fw)/2,oy0=(oh-fh)/2;for(int oy=0;oy<fh;oy++){double sy=((oy+.5)*r.h/fh)-.5;int y0=std::clamp((int)std::floor(sy),0,r.h-1),y1=std::min(y0+1,r.h-1);double fy=std::clamp(sy-std::floor(sy),0.0,1.0);for(int ox=0;ox<fw;ox++){double sx=((ox+.5)*r.w/fw)-.5;int x0=std::clamp((int)std::floor(sx),0,r.w-1),x1=std::min(x0+1,r.w-1);double fx=std::clamp(sx-std::floor(sx),0.0,1.0);size_t di=((size_t)(oy+oy0)*ow+(ox+ox0))*4;for(int ch=0;ch<4;ch++){auto at=[&](int x,int y){return (double)src[((size_t)(r.y+y)*sw+(r.x+x))*4+ch];};double top=at(x0,y0)+(at(x1,y0)-at(x0,y0))*fx,bot=at(x0,y1)+(at(x1,y1)-at(x0,y1))*fx,v=top+(bot-top)*fy;out[di+ch]=(std::uint8_t)std::lround(std::clamp(v,0.0,255.0));}}}return out;}
int main(int argc,char**argv){try{if(argc!=3){std::cerr<<"usage: crop_cards <repo-root> <card-crops.json>\n";return 2;}fs::path root=fs::weakly_canonical(argv[1]),mp=argv[2];std::ifstream in(mp);if(!in)throw std::runtime_error("MANIFEST_OPEN_FAILED");json m;in>>m;if(m.value("version",0)!=1)throw std::runtime_error("MANIFEST_VERSION_UNSUPPORTED");const auto&cards=m.at("cards");if(!cards.is_array()||cards.size()!=48)throw std::runtime_error("CARD_COUNT_MUST_BE_48");int ew=m.at("sourceWidth"),eh=m.at("sourceHeight"),ow=m.at("output").at("width"),oh=m.at("output").at("height");if(ow<=0||oh<=0||m.at("output").value("fit","")!="contain")throw std::runtime_error("INVALID_OUTPUT_SPEC");int sw=0,sh=0;auto src=read_png(root/m.at("source").get<std::string>(),sw,sh);if(sw!=ew||sh!=eh)throw std::runtime_error("SOURCE_DIMENSION_MISMATCH");std::set<std::string>ids,outs;std::vector<Rect>rs;int mc[13]{};for(const auto&c:cards){std::string id=c.at("id"),op=c.at("output");int month=c.at("month"),slot=c.at("slot");if(!ids.insert(id).second)throw std::runtime_error("DUPLICATE_CARD_ID:"+id);if(!outs.insert(op).second)throw std::runtime_error("DUPLICATE_OUTPUT:"+op);if(month<1||month>12||slot<1||slot>4)throw std::runtime_error("INVALID_MONTH_OR_SLOT:"+id);mc[month]++;const auto&q=c.at("crop");Rect r{q.at("x"),q.at("y"),q.at("width"),q.at("height")};if(r.w<=0||r.h<=0||r.x<0||r.y<0||r.x+r.w>sw||r.y+r.h>sh)throw std::runtime_error("CROP_OUT_OF_BOUNDS:"+id);for(const auto&old:rs)if(overlaps(r,old))throw std::runtime_error("CROP_OVERLAP:"+id);rs.push_back(r);}for(int mth=1;mth<=12;mth++)if(mc[mth]!=4)throw std::runtime_error("MONTH_CARD_COUNT_INVALID");for(size_t i=0;i<cards.size();i++)write_png(root/cards.at(i).at("output").get<std::string>(),ow,oh,contain(src,sw,rs[i],ow,oh));std::cout<<"PASS generated 48 lossless PNG cards at "<<ow<<"x"<<oh<<"\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
